export interface User{"payment_logs_id":3,
                        "manager":"José Cuevas",
                        "manager_id":1,"payment_date":"2023-01-12T07:00:00.000Z",
                        "payment_logs_num":"03",
                        "customer":"oswaldo",
                        "amount_of_payments":0,
                        "full_payment":1070,
                        "_day":"12",
                        "_month":"01",
                        "_year":"2023",
                        "producto":""}